### ISSUE TITLE
{options.outputDirLocalRepo} not working if moved to nx.json

### ISSUE THREAD

**Issue by jbadeau** [gridatek/jnxplus#746]
Hi there,

we normally keep common target settings in nx.json

```json
    "build"        : {
      "executor": "@jnxplus/nx-maven:run-task",
      "cache": true,
      "dependsOn": ["^build"],
      "outputs": ["{projectRoot}/target", "{options.outputDirLocalRepo}"]
      "inputs": ["production", "^production"],
      "options": {
        "task": "install -DskipTests=true"
      }
    },
```

however the {options.outputDirLocalRepo} does not resolve. The caching works fine when in project.json files.

perhaps the value is cached to early. Havent really looked into the code yet.

**Comment by khalilou88** [comment]
Hi @jbadeau 
I was not aware of this case. Will add it

**Comment by jbadeau** [comment]
Unfortunately there is another issue as well. Properties are not resolved either. We use revision as defined here https://maven.apache.org/maven-ci-friendly.html
To do this you may need to invoke Java code.

**Comment by khalilou88** [comment]
For target configuration in nx.json: https://github.com/khalilou88/jnxplus/pulls

**Comment by khalilou88** [comment]
@jbadeau Do you use the last version of the plugin. we use maven to find the effective version with `mvn help:evaluate`.
See this repo for examples: https://github.com/khalilou88/jnxplus-examples

**Comment by khalilou88** [comment]
@jbadeau please use version 0.22.10 for nx config.
For the second issue, I need more information

**Comment by jbadeau** [comment]
Works now
